### ISSUE TITLE
"Could not get unknown property 's3_key'." When trying to build using ./gradlew build

### ISSUE THREAD

**Issue by Voziv** [Slowpoke101/FTBLaunch#1003]
I wasn't able to get this project to compile due to a missing s3_key: Could not get unknown property 's3_key'. The command I used to attempt the build was ./gradlew build. I can't say I'm at all familiar with java projects so this might be something stupid simple that I've missed.

**Comment by progwml6** [comment]
its likely a bug introduced when i added s3 deployments a few months back to the launcher as i have s3 keys installed on all my computers, i likely never noticed it

**Comment by MikeSmith88** [comment]
If anyone cares I have committed a fix for this because I wanted to take a look at the code and could'nt compile myself. Quick gradle file fix.
