### ISSUE TITLE
Ram problem

### ISSUE THREAD

**Issue by plebania** [Slowpoke101/FTBLaunch#1006]
Hi, my problem is when i run ftb luncher im getting this console error:
Error while getting OS memory info: java.lang.NoSuchMethodException: com.ibm.lang.management.internal.UnixExtendedOperatingSystem.getTotalPhysicalMemorySize()
In luncher options max ram is set to 0GB and I can't change it. Surprisely when I ran the game it allocates 1GB of Ram, but it's to low amount of it :/
I'm using Linux mint 19 and openJDK java 8. pls help me,  I have looked for solution for a long time and found nothing.

**Comment by progwml6** [comment]
What launcher version are you running?

**Comment by plebania** [comment]
I'm not sure how to check it, but I downloaded it this week from official website so i suppose it's the newest one.

**Comment by jikuja** [comment]
Can you share launcher log?

**Comment by plebania** [comment]
Sure, here it is:
[log.txt](https://github.com/Slowpoke101/FTBLaunch/files/3111904/log.txt)

**Comment by jikuja** [comment]
FTB Luanhcer never been tested with other than Oracle's JRE and OpenJDK. Using other might cause problems.

You might be able to circumbent the problem be setting memory allocation in additional java flags.

**Comment by plebania** [comment]
Can you tell me how to do it or send me a guide?

**Comment by plebania** [comment]
ok sorry for troble... After about 6h of fight i forced java to work well witch ftbluncher, and it works just fine now
