### ISSUE TITLE
Vanilla laucher loses settings

### ISSUE THREAD

**Issue by Hero9909** [Slowpoke101/FTBLaunch#1012]
I'm using sdkman to install any version of java, but the Minecraft launcher does not seem to save the java path for any pack.

Or do the launcher overwrites the settings every time?

**Comment by jikuja** [comment]
This project is for old java based legacu FTB Launcher. It does not use vanilla launcher at all.

You are probably looking for: https://github.com/FTBTeam/FTB-App/issues/

**Comment by Hero9909** [comment]
woops, my fault
