### ISSUE TITLE
Gradlew build

### ISSUE THREAD

**Issue by castlerush** [Slowpoke101/FTBLaunch#888]
so when i used "gradlew build" in the cmd this error popped up.

C:\Users\david\Desktop\FTBLaunch-master\FTBLaunch-master>gradlew build

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\david\Desktop\FTBLaunch-master\FTBLaunch-master\build.gradl
e' line: 160

* What went wrong:
A problem occurred evaluating root project 'FTB_Launcher'.
> C:\Users\david\Desktop\FTBLaunch-master\FTBLaunch-master\.git\HEAD (The system
 cannot find the path specified)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 13.571 secs

C:\Users\david\Desktop\FTBLaunch-master\FTBLaunch-master>

**Comment by jikuja** [comment]
Should be fixed with: 2c09434e4eef69e31bc7124d64b4a33fc3f45804
