### ISSUE TITLE
Custom Modpacks

### ISSUE THREAD

**Issue by Immortalin** [Slowpoke101/FTBLaunch#918]
Hi,  can you add a option to create custom modpacks by directly downloading mods from the FTB launcher similar to the new launcher by Curse?

**Comment by jikuja** [comment]
Simple answer: no

- Where can we download mods? Curse does not offer API for mod metadata or mod download API
- FTB Launcher's lifetime is limited by backend. How long will be backend kept alive and updated after stable Curse client is released?
