### ISSUE TITLE
I keep crashing and i dont know why hope anyone can help (sorry for the rubbish title but if I knew what was wrong it would be fixed)

### ISSUE THREAD

**Issue by cannywolf** [Slowpoke101/FTBLaunch#941]
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 7/4/15 3:46 PM
Description: Ticking screen

java.lang.ClassCastException: com.flansmod.common.guns.EntityAAGun cannot be cast to net.minecraft.entity.EntityLivingBase
    at net.minecraft.client.network.NetHandlerPlayClient.func_147281_a(NetHandlerPlayClient.java:744)
    at net.minecraft.network.play.server.S0FPacketSpawnMob.func_148833_a(SourceFile:97)
    at net.minecraft.network.play.server.S0FPacketSpawnMob.func_148833_a(SourceFile:15)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1661)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.client.network.NetHandlerPlayClient.func_147281_a(NetHandlerPlayClient.java:744)
    at net.minecraft.network.play.server.S0FPacketSpawnMob.func_148833_a(SourceFile:97)
    at net.minecraft.network.play.server.S0FPacketSpawnMob.func_148833_a(SourceFile:15)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78)

-- Affected screen --
Details:
    Screen name: ~~ERROR~~ NullPointerException: null

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['AMoronicWolf'/854, l='MpServer', x=-29.50, y=68.62, z=-42.50]]
    Chunk stats: MultiplayerChunkCache: 75, 75
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-32,64,-36), Chunk: (at 0,4,12 in -2,-3; contains blocks -32,0,-48 to -17,255,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
    Level time: 56083 game time, 56083 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 39 total; [EntityCreeper['Creeper'/320, l='MpServer', x=-9.50, y=41.00, z=-49.00], EntityCreeper['Creeper'/321, l='MpServer', x=-11.78, y=40.00, z=-66.06], EntityZombie['Zombie'/323, l='MpServer', x=-84.50, y=17.00, z=16.50], EntityItem['item.item.reeds'/581, l='MpServer', x=32.66, y=63.13, z=-32.22], EntityItem['item.item.reeds'/583, l='MpServer', x=32.16, y=63.13, z=-27.34], EntityItem['item.tile.flower1.dandelion'/587, l='MpServer', x=10.69, y=63.13, z=-48.03], EntityZombie['Zombie'/461, l='MpServer', x=-87.50, y=22.00, z=-4.50], EntityZombie['Zombie'/463, l='MpServer', x=-90.50, y=22.00, z=-2.50], EntitySkeleton['Skeleton'/464, l='MpServer', x=-89.50, y=22.00, z=-1.50], EntityClientPlayerMP['AMoronicWolf'/854, l='MpServer', x=-29.50, y=68.62, z=-42.50], EntitySkeleton['Skeleton'/466, l='MpServer', x=-89.50, y=22.00, z=-4.50], EntityItem['item.item.reeds'/791, l='MpServer', x=32.84, y=63.13, z=-31.28], EntityCreeper['Creeper'/351, l='MpServer', x=-31.50, y=30.00, z=25.50], EntityCreeper['Creeper'/352, l='MpServer', x=-31.50, y=30.00, z=27.50], EntityBat['Bat'/808, l='MpServer', x=17.44, y=24.97, z=-61.91], EntitySkeleton['Skeleton'/489, l='MpServer', x=-8.56, y=33.00, z=-31.94], EntityZombie['Zombie'/169, l='MpServer', x=-0.84, y=29.00, z=-58.50], EntitySkeleton['Skeleton'/233, l='MpServer', x=-31.97, y=50.00, z=-68.44], EntityBat['Bat'/809, l='MpServer', x=17.41, y=29.09, z=-71.41], EntityWitch['Witch'/234, l='MpServer', x=-16.50, y=42.00, z=-66.09], EntityBat['Bat'/810, l='MpServer', x=20.38, y=20.56, z=-54.75], EntityWitch['Witch'/235, l='MpServer', x=-25.09, y=42.00, z=-57.50], EntityWitch['Witch'/236, l='MpServer', x=-30.50, y=49.00, z=-60.31], EntityZombie['Zombie'/494, l='MpServer', x=-61.50, y=50.00, z=12.50], EntityCreeper['Creeper'/562, l='MpServer', x=-38.50, y=54.00, z=4.50], EntityCreeper['Creeper'/499, l='MpServer', x=-83.50, y=25.00, z=16.50], EntityCreeper['Creeper'/500, l='MpServer', x=-83.50, y=25.00, z=15.50], EntitySkeleton['Skeleton'/439, l='MpServer', x=-5.50, y=33.00, z=-25.50], EntitySkeleton['Skeleton'/440, l='MpServer', x=-3.50, y=33.00, z=-22.50], EntityCreeper['Creeper'/441, l='MpServer', x=-5.50, y=33.00, z=-20.50], EntityBat['Bat'/378, l='MpServer', x=0.72, y=60.09, z=-46.59], EntityBat['Bat'/123, l='MpServer', x=-61.72, y=19.66, z=9.31], EntityEnderman['Enderman'/445, l='MpServer', x=-4.50, y=33.00, z=-20.50], EntityZombie['Zombie'/829, l='MpServer', x=-71.50, y=51.00, z=-96.50], EntityEnderman['Enderman'/446, l='MpServer', x=-8.50, y=33.00, z=-18.53], EntityZombie['Zombie'/318, l='MpServer', x=6.50, y=37.00, z=-77.50], EntityBat['Bat'/383, l='MpServer', x=12.97, y=22.09, z=-31.78], EntityBat['Bat'/959, l='MpServer', x=-5.50, y=41.00, z=-67.50], EntityEnderman['Enderman'/831, l='MpServer', x=-64.72, y=51.00, z=-96.47]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Non-integrated multiplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 457615128 bytes (436 MB) / 837500928 bytes (798 MB) up to 16092758016 bytes (15347 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx15G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 62 mods loaded, 61 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJA  mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJA  FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1448-1.7.10.jar) 
    UCHIJA  Forge{10.13.4.1448} [Minecraft Forge](forge-1.7.10-10.13.4.1448-1.7.10.jar) 
    UCHIJA  appliedenergistics2-core{rv1-stable-1} [AppliedEnergistics2 Core](minecraft.jar) 
    UCHIJA  CodeChickenCore{1.0.6.43} [CodeChicken Core](minecraft.jar) 
    UCHIJA  NotEnoughItems{1.0.4.90} [Not Enough Items](NotEnoughItems-1.7.10-1.0.4.90-universal.jar) 
    UCHIJA  ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) 
    UCHIJA  OpenModsCore{0.6} [OpenModsCore](minecraft.jar) 
    UCHIJA  <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UCHIJA  debug{1.0} [debug](denseores-1.6.2.jar) 
    UCHIJA  DamageIndicatorsMod{3.2.0} [Damage Indicators]([1.7.10]DamageIndicatorsMod-3.2.0.jar) 
    UCHIJA  appliedenergistics2{rv1-stable-1} [Applied Energistics 2](appliedenergistics2-rv1-stable-1.jar) 
    UCHIJA  asielib{0.2.7} [asielib](AsieLib-1.7.10-0.2.7.jar) 
    UCHIJA  BiblioCraft{1.9.2} [BiblioCraft](BiblioCraft[v1.9.2][MC1.7.10].jar) 
    UCHIJA  CoFHCore{1.7.10R3.0.2} [CoFH Core](CoFHCore-[1.7.10]3.0.2-262.jar) 
    UCHIJA  ThermalFoundation{1.7.10R1.0.0} [Thermal Foundation](ThermalFoundation-[1.7.10]1.0.0-81.jar) 
    UCHIJA  ThermalExpansion{1.7.10R4.0.1} [Thermal Expansion](ThermalExpansion-[1.7.10]4.0.1-182.jar) 
    UCHIJA  BigReactors{0.4.3A} [Big Reactors](BigReactors-0.4.3A.jar) 
    UCHIJA  AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry](BloodMagic-1.7.10-1.3.3-4.jar) 
    UCHIJA  BuildCraft|Core{7.0.12} [BuildCraft](buildcraft-7.0.12.jar) 
    UCHIJA  BuildCraft|Energy{7.0.12} [BC Energy](buildcraft-7.0.12.jar) 
    UCHIJA  BuildCraft|Factory{7.0.12} [BC Factory](buildcraft-7.0.12.jar) 
    UCHIJA  BuildCraft|Transport{7.0.12} [BC Transport](buildcraft-7.0.12.jar) 
    UCHIJA  BuildCraft|Builders{7.0.12} [BC Builders](buildcraft-7.0.12.jar) 
    UCHIJA  BuildCraft|Silicon{7.0.12} [BC Silicon](buildcraft-7.0.12.jar) 
    UCHIJA  BuildCraft|Robotics{7.0.12} [BC Robotics](buildcraft-7.0.12.jar) 
    UCHIJA  BuildCraft|Compat{7.0.8} [BuildCraft Compat](buildcraft-compat-7.0.8.jar) 
    UCHIJA  CarpentersBlocks{3.3.1} [Carpenter's Blocks](Carpenter's Blocks v3.3.1 - MC 1.7.10.jar) 
    UCHIJA  ChickenChunks{1.3.4.17} [ChickenChunks](ChickenChunks-1.7.10-1.3.4.17-universal.jar) 
    UCHIJA  chisel{1.5.6} [Chisel](Chisel-1.7.10-1.5.6.jar) 
    UCHIJA  thebombzenapi{2.4.1} [ThebombzenAPI](ThebombzenAPI-v2.4.1-mc1.7.2.jar) 
    UCHIJA  enchantview{4.0.4} [EnchantView](EnchantView-v4.0.4-mc1.7.10.jar) 
    UCHIJA  EnderIO{1.7.10-2.2.8.349} [Ender IO](EnderIO-1.7.10-2.2.8.349.jar) 
    UCHIJA  EnderStorage{1.4.7.33} [EnderStorage](EnderStorage-1.7.10-1.4.7.33-universal.jar) 
    UCHIJA  EnderTech{1.7.10-0.3.2.388} [EnderTech](EnderTech-1.7.10-0.3.2.388.jar) 
    UCHIJA  Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) 
    UCHIJA  ForgeMultipart{1.1.2.334} [Forge Multipart](ForgeMultipart-1.7.10-1.1.2.334-universal.jar) 
    UCHIJA  ExtraUtilities{1.2.0} [Extra Utilities](extrautilities-1.2.0.jar) 
    UCHIJA  FastCraft{1.19} [FastCraft](fastcraft-1.19.jar) 
    UCHIJA  flansmod{4.9.0} [Flan's Mod](Flans Mod-1.7.10-4.9.0.jar) 
    UCHIJA  iChunUtil{4.1.3} [iChunUtil](iChunUtil-4.1.3.jar) 
    UCHIJA  IC2{2.2.687-experimental} [IndustrialCraft 2](industrialcraft-2-2.2.687-experimental.jar) 
    UCHIJA  inventorytweaks{1.57-116} [Inventory Tweaks](InventoryTweaks-1.57-116.jar) 
    UCHIJA  IronChest{6.0.62.742} [Iron Chest](ironchest-1.7.10-6.0.62.742-universal.jar) 
    UCHIJA  JABBA{1.2.1} [JABBA](Jabba-1.2.1a_1.7.10.jar) 
    UCHIJA  Mantle{1.7.10-0.3.2.jenkins184} [Mantle](Mantle-1.7.10-0.3.2.jar) 
    UCHIJA  MapWriter{2.1.2} [MapWriter](MapWriter-1.7.10-2.1.2.jar) 
    UCHIJA  cfm{3.4.7} [§9MrCrayfish's Furniture Mod](MrCrayfishFurnitureModv3.4.7%281.7.10%29.jar) 
    UCHIJA  OpenMods{0.6} [OpenMods](OpenModsLib-1.7.10-0.6-snapshot-268.jar) 
    UCHIJA  OpenBlocks{1.3} [OpenBlocks](OpenBlocks-1.7.10-1.3-snapshot-512.jar) 
    UCHIJA  RedstoneArsenal{1.7.10R1.1.0} [Redstone Arsenal](RedstoneArsenal-[1.7.10]1.1.0-80.jar) 
    UCHIJA  statues{2.1.3} [Statues](statues-1.7.10-2.1.3.jar) 
    UCHIJA  TConstruct{1.7.10-1.7.1.build771} [Tinkers' Construct](TConstruct-1.7.10-1.7.1c.jar) 
    UCHIJA  Thaumcraft{4.2.2.1} [Thaumcraft](Thaumcraft-1.7.10-4.2.2.1.jar) 
    UCHIJA  ThaumicTinkerer{unspecified} [Thaumic Tinkerer](ThaumicTinkerer-2.5-1.7.10-502.jar) 
    UCHIJA  ThaumicExploration{0.6.0} [Thaumic Exploration](ThaumicExploration-1.7.10-1.1-37.jar) 
    UCHIJA  ThermalDynamics{1.7.10R1.0.0} [Thermal Dynamics](ThermalDynamics-[1.7.10]1.0.0-122.jar) 
    UCHIJA  Translocator{1.1.1.14} [Translocator](Translocator-1.7.10-1.1.1.14-universal.jar) 
    UCHIJA  McMultipart{1.1.2.334} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.2.334-universal.jar) 
    UCHIJA  denseores{1.0} [Dense Ores](denseores-1.6.2.jar) 
    UCHIJA  ForgeMicroblock{1.1.2.334} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.2.334-universal.jar) 
    UD  asielibcore{} [AsieLib CoreMod](minecraft.jar) 
    GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.4.13283 Compatibility Profile Context 14.501.1003.0' Renderer: 'AMD Radeon HD 7700 Series'
    OpenModsLib crash transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:ENABLED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
    AE2 Version: stable rv1-stable-1 for Forge 10.13.0.1187
    CoFHCore: -[1.7.10]3.0.2-262
    ThermalFoundation: -[1.7.10]1.0.0-81
    ThermalExpansion: -[1.7.10]4.0.1-182
    Mantle Environment: Environment healthy.
    RedstoneArsenal: -[1.7.10]1.1.0-80
    TConstruct Environment: Environment healthy.
    ThermalDynamics: -[1.7.10]1.0.0-122
    Stencil buffer state: Function set: GL30, pool: forge, bits: 8
    AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:OFF, BC:OFF, MJ6:OFF, MJ5:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:OFF, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
    Launched Version: 1.7.10-Forge10.13.4.1448-1.7.10
    LWJGL: 2.9.1
    OpenGL: AMD Radeon HD 7700 Series GL version 4.4.13283 Compatibility Profile Context 14.501.1003.0, ATI Technologies Inc.
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by TheWhoAreYouPerson** [comment]
First off I need to say that this isn't the place to post this, but since i have nothing better (and this issue isn't closed for whatever reason) to do ill try to point you in the right direction.

First, update flans mod to the latest version and see if its fixed (flans is the mod causing the crash)
Second, if it still crashing, go to [flan's Github issue page](https://github.com/FlansMods/FlansMod/issues?q=is%3Aissue+is%3Aopen) and if its not there, make a new [bug report.](http://vazkii.us/br101/)

Keep in mind that since he updated to 1.8, he may not be supporting 1.7.10 anymore, in which case you are stuck with it.
