### ISSUE TITLE
Mechanic to deprecate listed packs to pack codes

### ISSUE THREAD

**Issue by Watchful1** [Slowpoke101/FTBLaunch#950]
As discussed with prog, this would constitute adding a new file, almost certainly a json, with a set of foldername to pack code mappings. If a pack that was listed in the main modpacks.xml or thirdparty.xml is moved to a pack code, this file would be checked against installed modpack folders and the pack codes would be added if the modpack is installed.

Ideally this will be done by November 1st so packs can start being removed then.

**Comment by progwml6** [comment]
when implementing this we should add something to settings(off by default) that automatically adds the archived packs back to the lists
