### ISSUE TITLE
Launching the game uses a lot of RAM, compared to a few different launchers

### ISSUE THREAD

**Issue by SoniEx2** [Slowpoke101/FTBLaunch#956]
FTB Launcher uses well over 2GB of RAM when launching Minecraft (in addition to the 2GB used by Minecraft), while the vanilla launcher stays under 500MB, and MMC stays under 50MB.

**Comment by jikuja** [comment]
Well did you limit max allocated memory? Broken mods spamming console? Launcher version? Log?

**Comment by SoniEx2** [comment]
MultiMC is able to launch FTB instances and it does so without using over 2GB of RAM.

**Comment by jikuja** [comment]
Related topic: https://github.com/Slowpoke101/FTBLaunch/issues/859

Closing console window and disabling MC logging with command line argument should decrease memory usage but without proper bug report we can only guess why this particular installation used too much memory.

**Comment by SoniEx2** [comment]
Well why don't you actually try all edge cases instead of trying to guess?

**Comment by jikuja** [comment]
Well I won't waste my time with this ticket anymore.
