### ISSUE TITLE
Dont use interfaces like virbr0

### ISSUE THREAD

**Issue by Albritter** [Slowpoke101/FTBLaunch#976]
Since the login is encrypted using the MAC of the network interface of the computer it is not a god idea to use the MAC of interfaces like virbr0. Because these MACs change at certain times you will lose your login after for example reboot.

Ive added 
```
if (network.getName().startsWith("vir")) {
    continue;
}
```
at line 422 to 424 in `OSUtils` and it is working grate for me.
There my be more reliable ways of excluding such interfaces.

**Comment by progwml6** [comment]
can you PR this change please

**Comment by Albritter** [comment]
OK, I've done that
https://github.com/Slowpoke101/FTBLaunch/pull/977

**Comment by djfun** [comment]
is there no way to use the default network interface? on my computer the interface "docker0" is used, which also is just a virtual interface with a non-static mac address

**Comment by progwml6** [comment]
both of these interfaces will no longer be used as of c0998c5 . feel free to let us know of any other interfaces that are not persistant
