### ISSUE TITLE
Vanilla Magic (mod) fails to launch on FTB (works in MultiMC)

### ISSUE THREAD

**Issue by BionicFelps** [Slowpoke101/FTBLaunch#996]
Full log: https://pastebin.com/EuYn4hyp

Relevant error: java.lang.NoClassDefFoundError: jline/internal/InputStreamReader

TBH, not sure how this could be the launcher's fault, but I've narrowed down every other variable, this is the only one, if I directly copy the mods and config folder into a new multimc instance it works. If I launch with MultiMC's FTB support it doesn't, and if I launch with FTB it doesn't.  Presumably the FTB support works by invoking some part of the FTB launcher...

Forge versions are identical, all relevant files identical, LWJGL is the same as well.

**Comment by Watchful1** [comment]
MultiMC doesn't run any of the FTB launcher code.

Could you include a log of it starting successfully after copying? Try deleting the config/VanillaMagic file and letting it be recreated.

**Comment by BionicFelps** [comment]
Pastebin maximum upload exceeded, here's a gist...

Successful Launch: https://gist.github.com/BionicFelps/3df653afc63847e42c3ea105d550f73e

For bonus points, Failed attempt of MultiMC launching the FTB instance

https://pastebin.com/xmrgSmSU


I was thinking the FTB integration feature of MultiMC did use it, since it seemed to launch the FTB instance in place without requiring any additional information (such as forge version), but perhaps it just reads the info from the files FTB stores.


And same results when deleting config file, pasting configs of working versions in, etc.

**Comment by BionicFelps** [comment]
I believe I've found the difference!

/home/daniel/.local/share/multimc/libraries/jline/jline/2.13/jline-2.13.jar

MultiMC has this library in the libraries folder, and FTB doesn't.

**Comment by progwml6** [comment]
that's a mod bug jline is a server only library and does not exist in the client. some launchers use it anyway, in this case, a mod dev accidentally imported inputstreamreader from jline instead of the JDK

**Comment by Sejoslaw** [comment]
Please try newest version of VanillaMagic.
