### ISSUE TITLE
Curse modpacks list or search function?

### ISSUE THREAD

**Issue by ProxyNeko** [Slowpoke101/FTBLaunch#998]
It's been a while now (maybe two or three years) since I asked as well as many others if curse where going to support linux and they still say oh its not in the works but on the road map. In light of this would you be able to add in a tab to search for or list all the modpacks that are on curse as we are having to rely on hacky ways to get around this and they don't always work :(

Fingers crossed this can be considered because the linux community is kinda neglected by curse even though a lot of developers for mods use linux

My fingers are crossed for the best

**Comment by jikuja** [comment]
My Short Personal Answer: no

Why no:
1. There is no public and/or documented API to fetch metadata and files.
2. Adding other modpack source require huge code changes. Worth of used time? I and other members have wrote about this topic in forums: https://forum.feed-the-beast.com/threads/ftb-launcher-news.158980/page-18#post-1741264
3. Curse/Twitch ToS

Someone else from team might comment more about points 1 and 3

**Comment by progwml6** [comment]
there is no public api for curse mods/modpacks, and even the ones we that have been found are not considered "stable" long term, or very hard to work with from outside of .net

Ultimately, unless that changes I will not make tools/programs for users to install on their own computers that rely on these apis

**Comment by ProxyNeko** [comment]
I remember using an api of sorts from curse recently but I didn't look into it much so cant comment there

After reading through just some of the posts (out of the house currently) how about if we got the downloaded zip of the pack from curse and imported it? (May take this comment back when I get home and read them all)

Have not read through the curse ToS so cant say nothing about that lol who reads them (jk) I've asked them a few times and the community has tried to push them for support too with no luck so this was one of the few options I could come up with but you have my thanks for your swift reply I was expecting to wait quite a long time but it seams not lol
